[toolchain]
channel = "1.96.1"
profile = "default"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
targets = [
    "wasm32-unknown-unknown",
    "aarch64-linux-android",
    "aarch64-apple-ios",
    "x86_64-pc-windows-msvc",
]
