use crate::{emit_card, error::CardcError, parse_card_named, CardcResult};
use forge_carddef::{
    CardCatalog, CardClassification, CardDatabase, CardDefinition, IdentityRecord,
    SourceProvenance, CARD_DATABASE_MAGIC, CARD_DATABASE_SCHEMA_VERSION,
};
use serde::Serialize;
use std::{
    collections::BTreeSet,
    fs, io,
    path::{Path, PathBuf},
};

/// Inputs to a deterministic card database build.
#[derive(Clone, Copy, Debug)]
pub struct BuildOptions<'a> {
    /// File or directory containing `.frs` mechanics sources.
    pub input: &'a Path,
    /// Optional compact JSON catalog generated by forge-porttools.
    pub catalog: Option<&'a Path>,
    /// Binary database destination.
    pub output: &'a Path,
}

/// Deterministic database build summary.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BuildReport {
    /// Compiled mechanics definition count.
    pub definition_count: usize,
    /// Definitions that passed parse/emit/reparse equality.
    pub roundtrip_count: usize,
    /// Catalog identity count.
    pub identity_count: usize,
    /// Catalog printing count.
    pub printing_count: usize,
    /// Binary byte count.
    pub byte_count: usize,
    /// Binary output path.
    pub output: PathBuf,
    /// JSON index output path.
    pub index: PathBuf,
}

/// Builds a deterministic database and inspectable JSON index.
pub fn build_card_database(options: BuildOptions<'_>) -> CardcResult<BuildReport> {
    let mut files = Vec::new();
    collect_frs_files(options.input, &mut files).map_err(|error| io_error(options.input, error))?;
    files.sort();
    if files.is_empty() {
        return Err(CardcError::new(
            options.input.display().to_string(),
            1,
            1,
            "no .frs card sources found",
        ));
    }

    let mut definitions = Vec::with_capacity(files.len());
    for file in files {
        let source = fs::read_to_string(&file).map_err(|error| io_error(&file, error))?;
        let display = display_relative(options.input, &file);
        let definition = parse_card_named(&display, &source)?;
        let emitted = emit_card(&definition);
        let reparsed = parse_card_named(&display, &emitted)?;
        if reparsed != definition {
            return Err(CardcError::new(
                display,
                1,
                1,
                "canonical round-trip changed the card definition",
            ));
        }
        definitions.push(definition);
    }
    definitions.sort_by(|left, right| left.id.cmp(&right.id));
    validate_unique_definitions(&definitions)?;

    let mut database = match options.catalog {
        Some(path) => database_from_catalog(path)?,
        None => database_from_definitions(&definitions),
    };
    apply_definition_statuses(&mut database, &definitions, options.catalog.is_some())?;
    database.definitions = definitions;
    validate_database(&database)?;

    let bytes = encode_card_database(&database)?;
    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).map_err(|error| io_error(parent, error))?;
    }
    fs::write(options.output, &bytes).map_err(|error| io_error(options.output, error))?;

    let index_path = options.output.with_extension("index.json");
    let index = IndexDocument::from_database(&database);
    let index_bytes = serde_json::to_vec_pretty(&index).map_err(|error| {
        CardcError::new(index_path.display().to_string(), 1, 1, error.to_string())
    })?;
    fs::write(&index_path, index_bytes).map_err(|error| io_error(&index_path, error))?;

    Ok(BuildReport {
        definition_count: database.definitions.len(),
        roundtrip_count: database.definitions.len(),
        identity_count: database.identities.len(),
        printing_count: database.printings.len(),
        byte_count: bytes.len(),
        output: options.output.to_path_buf(),
        index: index_path,
    })
}

/// Encodes one database with Forge magic, schema, and deterministic bincode payload.
pub fn encode_card_database(database: &CardDatabase) -> CardcResult<Vec<u8>> {
    let config = bincode::config::standard()
        .with_fixed_int_encoding()
        .with_little_endian();
    let payload = bincode::serde::encode_to_vec(database, config).map_err(|error| {
        CardcError::new(
            "<database>",
            1,
            1,
            format!("bincode encode failed: {error}"),
        )
    })?;
    let mut bytes = Vec::with_capacity(CARD_DATABASE_MAGIC.len() + 4 + payload.len());
    bytes.extend_from_slice(&CARD_DATABASE_MAGIC);
    bytes.extend_from_slice(&CARD_DATABASE_SCHEMA_VERSION.to_le_bytes());
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

fn database_from_catalog(path: &Path) -> CardcResult<CardDatabase> {
    let bytes = fs::read(path).map_err(|error| io_error(path, error))?;
    let catalog: CardCatalog = serde_json::from_slice(&bytes)
        .map_err(|error| CardcError::new(path.display().to_string(), 1, 1, error.to_string()))?;
    Ok(CardDatabase {
        schema_version: catalog.schema_version,
        provenance: catalog.provenance,
        identities: catalog.identities,
        printings: catalog.printings,
        definitions: Vec::new(),
    })
}

fn database_from_definitions(definitions: &[CardDefinition]) -> CardDatabase {
    let provenance = SourceProvenance {
        source: "Forge card DSL".to_string(),
        source_path: "cards".to_string(),
        source_updated_at: String::new(),
        source_sha256: String::new(),
        generator: format!("forge-cardc {}", env!("CARGO_PKG_VERSION")),
    };
    let mut database = CardDatabase::empty(provenance);
    database.identities = definitions
        .iter()
        .map(|definition| IdentityRecord {
            id: definition.id.clone(),
            name: definition.name.clone(),
            layout: definition.layout,
            face_names: definition
                .faces
                .iter()
                .map(|face| face.name.clone())
                .collect(),
            classification: definition.status.clone(),
        })
        .collect();
    database
}

fn apply_definition_statuses(
    database: &mut CardDatabase,
    definitions: &[CardDefinition],
    require_catalog_identity: bool,
) -> CardcResult<()> {
    for definition in definitions {
        let identity = database
            .identities
            .iter_mut()
            .find(|identity| identity.id == definition.id);
        match identity {
            Some(identity) => identity.classification = definition.status.clone(),
            None if require_catalog_identity => {
                return Err(CardcError::new(
                    "<database>",
                    1,
                    1,
                    format!(
                        "definition {} has no catalog identity",
                        definition.id.as_str()
                    ),
                ))
            }
            None => {}
        }
    }
    Ok(())
}

fn validate_unique_definitions(definitions: &[CardDefinition]) -> CardcResult<()> {
    let mut ids = BTreeSet::new();
    for definition in definitions {
        if !ids.insert(definition.id.as_str()) {
            return Err(CardcError::new(
                "<database>",
                1,
                1,
                format!("duplicate definition id `{}`", definition.id.as_str()),
            ));
        }
    }
    Ok(())
}

fn validate_database(database: &CardDatabase) -> CardcResult<()> {
    if database.schema_version != CARD_DATABASE_SCHEMA_VERSION {
        return Err(CardcError::new(
            "<database>",
            1,
            1,
            format!("unsupported catalog schema {}", database.schema_version),
        ));
    }
    let mut identity_ids = BTreeSet::new();
    for identity in &database.identities {
        if !identity_ids.insert(identity.id.as_str()) {
            return Err(CardcError::new(
                "<database>",
                1,
                1,
                format!("duplicate identity `{}`", identity.id.as_str()),
            ));
        }
    }
    let mut printing_ids = BTreeSet::new();
    for printing in &database.printings {
        if !printing_ids.insert(printing.id.as_str()) {
            return Err(CardcError::new(
                "<database>",
                1,
                1,
                format!("duplicate printing `{}`", printing.id.as_str()),
            ));
        }
        if !identity_ids.contains(printing.oracle_id.as_str()) {
            return Err(CardcError::new(
                "<database>",
                1,
                1,
                format!(
                    "printing {} references missing identity {}",
                    printing.id.as_str(),
                    printing.oracle_id.as_str()
                ),
            ));
        }
    }
    Ok(())
}

fn collect_frs_files(path: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    if path.is_file() {
        if path.extension().is_some_and(|extension| extension == "frs") {
            files.push(path.to_path_buf());
        }
        return Ok(());
    }
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        collect_frs_files(&entry.path(), files)?;
    }
    Ok(())
}

fn display_relative(root: &Path, file: &Path) -> String {
    if root.is_dir() {
        file.strip_prefix(root).map_or_else(
            |_error| file.display().to_string(),
            |path| path.display().to_string(),
        )
    } else {
        file.file_name().map_or_else(
            || "<card>".to_string(),
            |name| name.to_string_lossy().into_owned(),
        )
    }
}

fn io_error(path: &Path, error: io::Error) -> CardcError {
    CardcError::new(path.display().to_string(), 1, 1, error.to_string())
}

#[derive(Serialize)]
struct IndexDocument<'a> {
    schema_version: u32,
    identities: Vec<IndexIdentity<'a>>,
    printings: Vec<IndexPrinting<'a>>,
}

impl<'a> IndexDocument<'a> {
    fn from_database(database: &'a CardDatabase) -> Self {
        Self {
            schema_version: database.schema_version,
            identities: database
                .identities
                .iter()
                .map(|identity| IndexIdentity {
                    id: identity.id.as_str(),
                    name: &identity.name,
                    layout: identity.layout.as_str(),
                    classification: classification_name(&identity.classification),
                })
                .collect(),
            printings: database
                .printings
                .iter()
                .map(|printing| IndexPrinting {
                    id: printing.id.as_str(),
                    oracle_id: printing.oracle_id.as_str(),
                    set_code: &printing.set_code,
                    collector_number: &printing.collector_number,
                })
                .collect(),
        }
    }
}

#[derive(Serialize)]
struct IndexIdentity<'a> {
    id: &'a str,
    name: &'a str,
    layout: &'a str,
    classification: &'a str,
}

#[derive(Serialize)]
struct IndexPrinting<'a> {
    id: &'a str,
    oracle_id: &'a str,
    set_code: &'a str,
    collector_number: &'a str,
}

fn classification_name(classification: &CardClassification) -> &'static str {
    match classification {
        CardClassification::VerifiedPlayable => "verified_playable",
        CardClassification::UnverifiedPlayable => "unverified_playable",
        CardClassification::Quarantined(_) => "quarantined",
        CardClassification::OutOfV1(_) => "out_of_v1",
        CardClassification::CatalogOnly(_) => "catalog_only",
    }
}
